// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrbqpvabvkukijvelyzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYnFwdmFidmt1a2lqdmVseXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjkwNDgsImV4cCI6MjA2NjA0NTA0OH0.U984DBFxWjI05OOwEHbkkI0t_j2DgcBly2egHeId3sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);